### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by adriangb** [viz-rs/path-tree#12]
Just FYI, I thought this was cool and made a Python wrapper: https://pypi.org/project/routrie/

**Comment by fundon** [comment]
That's cool! Thank you. :)

**Comment by adriangb** [comment]
No problem! Thank the PyO3 authors.

**Comment by adriangb** [comment]
I closed the issue since you saw it to avoid clutter. But feel free to add a link to your readme or something, if you want.

**Comment by fundon** [comment]
@adriangb Ok, I like that.

**Comment by fundon** [comment]
@adriangb PR plz.

**Comment by adriangb** [comment]
#13
